### ISSUE TITLE
🐛 First ROM's box image not loaded

### ISSUE THREAD

**Issue by jeremyhalin** [djfumberger/retromini#2]
I noticed that when I press A to select and enter a games' collection, the first game's image is not loaded.
In fact, the theme shows the previously selected game of another collection.
An idea would be to trigger the event of "scrolling" to a new game, but with selecting the first item in the list, I don't know.

**Comment by djfumberger** [comment]
Thanks Jeremy, hopefully have addressed the various issues in caad5c838006f1fbf572978eeff4f29c7f5f7e30
